---
title: "data_challenge2"
author: "Maya Lu, Emaneula Beale,James Lee"
date: "3/6/2021"
output: html_document
---

## 1. SET UP
```{r}
rm(list = ls())
library(tidyr)
emails <- read.csv("Clinton.csv")
table(emails$Recipient)

# create normalized version of dtm
dtm <- emails[, 10:3009]
row_lengths = apply(dtm, 1, function(z) sqrt(sum(z^2)))
dtm_norm <- dtm/row_lengths
dtm_norm <- na.omit(dtm_norm)

neg <- unlist(read.table("negative-words.txt", stringsAsFactors = F))
pos <- unlist(read.table("positive-words.txt", stringsAsFactors = F))
```


# 2. K-MEANS CLUSTERING
```{r}
k <- 10
k10_norm <- kmeans(dtm_norm, centers = k, nstart = 3)
k10 <- kmeans(dtm, centers = k, nstart = 3)

table(k10$cluster)

# view clusters
k10_freqWords <- data.frame(
  cluster1 = rep(NA, 10),
  cluster2 = rep(NA, 10),
  cluster3 = rep(NA, 10),
  cluster4 = rep(NA, 10),
  cluster5 = rep(NA, 10),
  cluster6 = rep(NA, 10),
  cluster7 = rep(NA, 10),
  cluster8 = rep(NA, 10),
  cluster9 = rep(NA, 10),
  cluster10 = rep(NA, 10)
)

# Most frequent words
for (i in 1:10) {
  clu <- i
  centroid.i <- k10$centers[clu,]
  k10_freqWords[,i] <- names(sort(centroid.i, decreasing = T)[1:10])
}


# Most distinct words
k10_distWords <- data.frame(
  cluster1 = rep(NA, 10),
  cluster2 = rep(NA, 10),
  cluster3 = rep(NA, 10),
  cluster4 = rep(NA, 10),
  cluster5 = rep(NA, 10),
  cluster6 = rep(NA, 10),
  cluster7 = rep(NA, 10),
  cluster8 = rep(NA, 10),
  cluster9 = rep(NA, 10),
  cluster10 = rep(NA, 10)
)


for (i in 1:10) {
  clu <- i
  centroid.i <- k10$centers[clu,]
  centroid.noti <- apply(k10$centers[-clu,], 2, mean)
  k10_distWords[,i] <- names(sort(centroid.i - centroid.noti, decreasing = T)[1:10])
}

rm(k10, k10_distWords, k10_freqWords) #remove irrelevant variables

```


```{r}

```


